# Generated by Django 4.2 on 2023-04-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time_diff',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
