# Generated by Django 4.2 on 2023-04-30 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
