# Generated by Django 4.2 on 2023-04-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_active_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
